### ISSUE TITLE
DIfferent renponses when using line break in text area input 

### ISSUE THREAD

**Issue by lakshit1001** [human-divanshu/Text-to-Sign-Language#1]
![image](https://cloud.githubusercontent.com/assets/6951276/23337108/6d77f96a-fc09-11e6-8208-8a463e2538be.png)
gives error if we use enter in the text area
vs without the enter
![image](https://cloud.githubusercontent.com/assets/6951276/23337113/7ef1dd46-fc09-11e6-9743-3ca755b25ec1.png)

**Comment by human-divanshu** [comment]
Issue to parser has been noted down and will be resolved in next release.
