### ISSUE TITLE
How to run this Project? README is missing

### ISSUE THREAD

**Issue by zainulabidin302** [human-divanshu/Text-to-Sign-Language#2]
Hello, 

It was great to see your project. I appreciate your effort on such a great cause. 

In essence, this project is similar to the one we are doing at University of Management and Technology. 
Here is a research paper which you might be interested in seeing this 
https://www.researchgate.net/publication/260762401_A_Vision_Based_Approach_for_Pakistan_Sign_Language_alphabets_Recognition & http://pu.edu.pk/images/journal/csas/PDF/24%20Nabeel%20Sabir_30_2.pdf.

I wanted to run this project on my machine. I am able to run the PHP part. I want to recreate the whole system on my machine. The database users for admin is available but other resources are missing.

Can you write a readme on how to recreate the whole project?

**Comment by human-divanshu** [comment]
Hello,

We are working on the refactoring of the codebase. This is the codebase for the prototype. We will soon release a version with API for the avatar.
Here is the specification of the avatar API we are working on
https://docs.google.com/presentation/d/1t_46INZg7HDgz9B5PtDkFsFdihb1__fmsPMqAQEMB8Y/edit?usp=sharing

Please wait for few weeks while we do this.
You can contact the research head directly at parteek.bhatia@thapar.edu and me at human.divanshu@gmail.com

With regards
Divanshu Singh
